# Generated by Django 5.2.6 on 2025-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicationreminder_last_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='precision_minutes',
            field=models.IntegerField(default=2, help_text='How many minutes before/after exact time to trigger reminder'),
        ),
    ]
